# Generated by Django 5.2.1 on 2025-12-22 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('group_sessions', '0003_groupsession_end_time'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='group_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='group_sessions.groupsession'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('group_session__isnull', True)), models.Q(('course__isnull', True), ('group_session__isnull', False)), models.Q(('course__isnull', True), ('group_session__isnull', True)), _connector='OR'), name='only_one_content_type'),
        ),
    ]
