# Generated by Django 5.2.1 on 2025-12-23 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chate_box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_url',
        ),
    ]
