# Generated by Django 5.2.1 on 2025-12-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chate_box', '0002_remove_message_file_name_remove_message_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='blocked_content_type',
            field=models.CharField(blank=True, help_text='Comma-separated list of blocked content types: email, phone, social_link', max_length=100),
        ),
    ]
