# Generated by Django 5.2.1 on 2025-12-27 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('individual_live_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_class_datetime', models.DateTimeField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_demo_free', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='individual_live_class.liveclassschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_invitations', to='authentication.studentprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_class_invitations', to='authentication.teacherprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
