# Generated by Django 5.2.1 on 2025-11-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='budget_type',
            field=models.CharField(choices=[('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('total', 'Total Amount'), ('fixed', 'Fixed')], default='per_hour', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='teaching_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('in person', 'In Person')], default='remote', max_length=10),
        ),
    ]
