# Generated by Django 5.2.1 on 2025-11-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0002_alter_jobpost_budget_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='duration_unit',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='hours', help_text='e.g., hours, days, sessions', max_length=20),
        ),
    ]
