# Generated by Django 5.2.1 on 2025-12-22 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('courses', '0001_initial'),
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', through='courses.Enrollment', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='linked_job',
            field=models.OneToOneField(blank=True, help_text='Job post created from this query', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_board.jobpost'),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='User account if they registered later', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='courses_created',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['curriculum'], name='authenticat_curricu_bc999b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['tutor_gender'], name='authenticat_tutor_g_271fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['email'], name='student_que_email_57d4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['is_registered'], name='student_que_is_regi_8316d1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['is_processed'], name='student_que_is_proc_7dd6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['created_at'], name='student_que_created_4b91b7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['years_of_experience'], name='authenticat_years_o_2e206f_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['average_rating'], name='authenticat_average_1177eb_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['status'], name='authenticat_status_159934_idx'),
        ),
    ]
