# Generated by Django 5.2.1 on 2025-10-27 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_students', through='courses.Enrollment', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='linked_user',
            field=models.ForeignKey(blank=True, help_text='User account if they registered later', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='courses_created',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='courses.course'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['education_level', 'graduation_year'], name='authenticat_educati_11e0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['employment_status'], name='authenticat_employm_f92183_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['email'], name='student_que_email_57d4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['is_registered'], name='student_que_is_regi_8316d1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['is_processed'], name='student_que_is_proc_7dd6b0_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['created_at'], name='student_que_created_4b91b7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['expertise_level', 'years_of_experience'], name='authenticat_experti_c1bb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['average_rating'], name='authenticat_average_1177eb_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['status'], name='authenticat_status_159934_idx'),
        ),
    ]
