# Generated by Django 5.2.1 on 2025-12-18 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentquery',
            name='student_que_is_regi_8316d1_idx',
        ),
        migrations.AddField(
            model_name='studentquery',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='job_post_id',
            field=models.CharField(blank=True, help_text='ID of the job post created from this query', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Job')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='user',
            field=models.ForeignKey(help_text='Registered user who submitted this query', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['status'], name='student_que_status_46f40e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['user'], name='student_que_user_id_b851a5_idx'),
        ),
    ]
