# Generated by Django 5.2.1 on 2025-12-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_studentquery_student_que_is_regi_8316d1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentquery',
            name='student_que_status_46f40e_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentquery',
            name='student_que_user_id_b851a5_idx',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='converted_at',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='job_post_id',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='user',
        ),
        migrations.AddIndex(
            model_name='studentquery',
            index=models.Index(fields=['is_registered'], name='student_que_is_regi_8316d1_idx'),
        ),
    ]
