# Generated by Django 5.2.1 on 2025-12-18 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_studentquery_student_que_status_46f40e_idx_and_more'),
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquery',
            name='linked_job',
            field=models.OneToOneField(blank=True, help_text='Job post created from this query', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_board.jobpost'),
        ),
    ]
