# Generated by Django 5.2.1 on 2025-12-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='page_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
