# Generated by Django 5.2.1 on 2025-12-22 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=300)),
                ('subject', models.JSONField(blank=True, default=list, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('days', models.JSONField(blank=True, default=list, null=True)),
                ('start_time', models.DateTimeField()),
                ('class_duration', models.IntegerField(default=60)),
                ('session_duration', models.IntegerField(default=1, help_text='duration of session in months')),
                ('max_students', models.IntegerField(default=20)),
                ('min_students', models.IntegerField(default=5)),
                ('current_enrollments', models.IntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='GroupSessionEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('joined_at', models.JSONField(blank=True, null=True)),
                ('left_at', models.JSONField(blank=True, null=True)),
                ('attendance_duration', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
    ]
