# Generated by Django 5.2.1 on 2025-12-22 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_sessions', '0001_initial'),
        ('meetings', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_session_instance', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='groupsession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupsessionenrollment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='groupsessionenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='group_sessions.groupsession'),
        ),
        migrations.AddField(
            model_name='groupsessionenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_session_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='groupsession',
            index=models.Index(fields=['status', 'start_time'], name='group_sessi_status_752e89_idx'),
        ),
        migrations.AddIndex(
            model_name='groupsession',
            index=models.Index(fields=['teacher', 'status'], name='group_sessi_teacher_d8638a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsessionenrollment',
            unique_together={('session', 'student')},
        ),
    ]
