# Generated by Django 5.2.1 on 2025-12-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_sessions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
