# Generated by Django 5.2.1 on 2025-12-22 18:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_sessions', '0003_groupsession_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsessionenrollment',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='groupsessionenrollment',
            name='left_at',
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='group_sessions.groupsessionenrollment')),
            ],
            options={
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['enrollment', 'joined_at'], name='group_sessi_enrollm_12c9a5_idx')],
            },
        ),
    ]
